version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=aviata
      - RABBITMQ_DEFAULT_PASS=aviata
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    depends_on:
      - rabbitmq
      - redis
  celerybeat:
    build: .
    depends_on:
      - rabbitmq
      - redis
      - celery
    entrypoint: ["celery", "-A", "aviata.celery_app", "beat", "--loglevel=info"]
  web:
    build: .
    depends_on:
      - rabbitmq
      - redis
      - celery
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
    entrypoint: ["flask", "run", "--host=0.0.0.0"]
